### PR TITLE
Lowers deployment target to 8.0

### PR DESCRIPTION
**Pull request by jasonmerino**
For apps that have their deployment target set to iOS 8.0 the current settings for iPhone deployment target being set to 9.2 causes the app to not be able to run.

### CODE REVIEW

**Comment by jasonmerino** [comment]
@jdee Thanks for the quick merge on this! Any idea when the next release is going to go out on npm?

**Comment by jdee** [comment]
@jasonmerino I'll do a release later today. Thanks for finding this.

**Comment by jasonmerino** [comment]
@jdee AWESOME! For sure. :)

**Comment by ethanneff** [comment]
Hello @jasonmerino,

Branch wants to thank you for your help. Please email to eneff@branch.io and we will send you a free gift.

Best

**Pull request merged**
