### PR TITLE
Updated build tools / sdk to work with react-native 0.56+

### PR DESCRIPTION
**Pull request by danilobuerger**

### CODE REVIEW

**Comment by danilobuerger** [comment]
ping @sequoiaat @aaaronlopez

**Comment by sequoiaat** [comment]
@aaaronlopez  kindly merge the PR

**Comment by Sarkar** [comment]
👍

**Comment by vomchik** [comment]
Who can release a beta version to npm?

**Comment by vomchik** [comment]
@Sarkar do you have permissions to npm?

**Pull request merged**
